#!/bin/bash

if [[ -e "MacOSX10.4.Universal.pkg" ]]
then
	echo "*** Missing 10.4 Apple SDK ***"
else
	xar -xf MacOSX10.4.Universal.pkg && zcat Payload |cpio -di
	rm Bom Payload Scripts PackageInfo
	cp -a SDKs/MacOSX10.4u.sdk apple-uni-sdk-10.4u-dummy
	cd apple-uni-sdk-10.4u-dummy
	dpkg-buildpackage -uc -b
	cd ..
fi

if [[ -e "MacOSX10.5.pkg" ]]
then
	echo "*** Missing 10.5 Apple SDK ***"
else
	xar -xf MacOSX10.5.pkg && zcat Payload |cpio -di
	rm Bom Payload Scripts PackageInfo
	cp -a SDKs/MacOSX10.5.sdk apple-uni-sdk-10.5-dummy
	cd apple-uni-sdk-10.5-dummy
	dpkg-buildpackage -uc -b
	cd ..
fi

if [[ -e "MacOSX10.6.pkg" ]]
then
	echo "*** Missing 10.6 Apple SDK ***"
else
	xar -xf MacOSX10.6.pkg && zcat Payload |cpio -di
	rm Bom Payload Scripts PackageInfo
	cp -a SDKs/MacOSX10.6.sdk apple-uni-sdk-10.6-dummy
	cd apple-uni-sdk-10.6-dummy
	dpkg-buildpackage -uc -b
	cd ..
fi

